Document: thrift-fb303
Title: Debian thrift-fb303 Manual
Author: <insert document author here>
Abstract: This manual describes what thrift-fb303 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/thrift-fb303/thrift-fb303.sgml.gz

Format: postscript
Files: /usr/share/doc/thrift-fb303/thrift-fb303.ps.gz

Format: text
Files: /usr/share/doc/thrift-fb303/thrift-fb303.text.gz

Format: HTML
Index: /usr/share/doc/thrift-fb303/html/index.html
Files: /usr/share/doc/thrift-fb303/html/*.html

  
